# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        
    - name: Use Node.js
      uses: actions/setup-node@v4 # Step 2: Set up Node.js environment
      with:
        node-version: '24' # Specify the Node.js version

    - name: Restore dependencies Abdtractions
      run: dotnet restore TruckDown.Client.Abstractions/TruckDown.Client.Abstractions.csproj

    - name: Restore dependencies Client
      run: dotnet restore TruckDown.Client/TruckDown.Client.csproj

    - name: Restore dependencies Client - npm
      run: npm install
      working-directory: ./TruckDown.Client
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_APIKEY }}

    - name: Build Abstractions
      run: dotnet build --configuration Release TruckDown.Client.Abstractions/TruckDown.Client.Abstractions.csproj --no-restore -p RunNumber=${{ github.run_number }}

    - name: Build Client
      run: dotnet build --configuration Release TruckDown.Client/TruckDown.Client.csproj --no-restore -p RunNumber=${{ github.run_number }}

    - name: Build Client - npm
      working-directory: ./TruckDown.Client
      run: npm run build

    - name: Test Abstractions
      run: dotnet test --no-build --verbosity normal TruckDown.Client.Abstractions/TruckDown.Client.Abstractions.csproj

    - name: Test Client
      run: dotnet test --no-build --verbosity normal TruckDown.Client/TruckDown.Client.csproj

    - name: Test Client - npm
      working-directory: ./TruckDown.Client
      run: npm run test

    - name: Pack Abstractions
      run: dotnet pack --configuration Release TruckDown.Client.Abstractions/TruckDown.Client.Abstractions.csproj --no-restore -p RunNumber=${{ github.run_number }}

    - name: Pack Client
      run: dotnet pack --configuration Release TruckDown.Client/TruckDown.Client.csproj --no-restore -p RunNumber=${{ github.run_number }}

    #- name: PublishA bstractions
    #  run: dotnet nuget push "TruckDown.Client.Abstractions/bin/Release/TruckDown.Client.Abstractions.1.0.${{ github.run_number }}.nupkg" --api-key  ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json

    #- name: Publish Client
    #  run: dotnet nuget push "TruckDown.Client/bin/Release/TruckDown.Client.1.0.${{ github.run_number }}.nupkg" --api-key  ${{ secrets.NUGET_APIKEY }} --source https://api.nuget.org/v3/index.json
    
    - name: Publish Client - npm
      run: npm publish --access public
      working-directory: ./TruckDown.Client
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_APIKEY }}
      
